-- Baseline migration capturing the entire schema as of branch
-- claude/nutritrack-full-stack-D8zvm. Generated by hand because the
-- session never had a writable Postgres to run `prisma migrate dev`
-- against. Verify with `prisma migrate diff` before applying to a
-- live environment.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- Users + auth
-- ============================================================

CREATE TABLE "users" (
  "id"            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "email"         VARCHAR(255) NOT NULL UNIQUE,
  "password_hash" VARCHAR(255) NOT NULL,
  "full_name"     VARCHAR(100),
  "avatar_url"    TEXT,
  "goal"          VARCHAR(50),
  "timezone"      VARCHAR(50) NOT NULL DEFAULT 'UTC',
  "unit_system"   VARCHAR(10) NOT NULL DEFAULT 'metric',
  "role"          VARCHAR(20) NOT NULL DEFAULT 'user',
  "created_at"    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at"    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "refresh_tokens" (
  "id"          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"     UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "token_hash"  VARCHAR(128) NOT NULL,
  "expires_at"  TIMESTAMPTZ NOT NULL,
  "revoked_at"  TIMESTAMPTZ,
  "created_at"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "user_agent"  TEXT
);
CREATE INDEX "idx_refresh_tokens_user_revoked" ON "refresh_tokens"("user_id", "revoked_at");

CREATE TABLE "coach_links" (
  "id"          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "coach_id"    UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "client_id"   UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "accepted_at" TIMESTAMPTZ,
  "created_at"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "coach_links_coach_client_unique" UNIQUE ("coach_id", "client_id")
);
CREATE INDEX "idx_coach_links_client_accepted" ON "coach_links"("client_id", "accepted_at");

-- ============================================================
-- Profile + tracking
-- ============================================================

CREATE TABLE "user_profiles" (
  "id"                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"             UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "height_cm"           DECIMAL(5,1),
  "weight_kg"           DECIMAL(5,1),
  "body_fat_pct"        DECIMAL(4,1),
  "waist_cm"            DECIMAL(5,1),
  "date_of_birth"       DATE,
  "gender"              VARCHAR(20),
  "activity_level"      VARCHAR(30),
  "daily_water_goal_ml" INTEGER NOT NULL DEFAULT 2500,
  "recorded_at"         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "water_logs" (
  "id"        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"   UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "date"      DATE NOT NULL,
  "amount_ml" INTEGER NOT NULL,
  "logged_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX "idx_water_logs_user_date" ON "water_logs"("user_id", "date");

CREATE TABLE "body_logs" (
  "id"            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"       UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "date"          DATE NOT NULL,
  "weight_kg"     DECIMAL(5,1),
  "waist_cm"      DECIMAL(5,1),
  "body_fat_pct"  DECIMAL(4,1),
  "energy_level"  INTEGER,
  "hunger_level"  INTEGER,
  "sleep_quality" INTEGER,
  "photo_url"     TEXT,
  "notes"         TEXT,
  "created_at"    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX "idx_body_logs_user_date" ON "body_logs"("user_id", "date");

CREATE TABLE "daily_notes" (
  "id"         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"    UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "date"       DATE NOT NULL,
  "symptoms"   JSONB,
  "mood"       INTEGER,
  "notes"      TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX "idx_daily_notes_user_date" ON "daily_notes"("user_id", "date");

CREATE TABLE "notification_settings" (
  "id"                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"             UUID NOT NULL UNIQUE REFERENCES "users"("id") ON DELETE CASCADE,
  "push_enabled"        BOOLEAN NOT NULL DEFAULT TRUE,
  "meal_reminder"       BOOLEAN NOT NULL DEFAULT TRUE,
  "supplement_reminder" BOOLEAN NOT NULL DEFAULT TRUE,
  "water_reminder"      BOOLEAN NOT NULL DEFAULT TRUE,
  "overdue_reminder"    BOOLEAN NOT NULL DEFAULT TRUE,
  "advance_minutes"     INTEGER NOT NULL DEFAULT 5,
  "quiet_start"         TIME,
  "quiet_end"           TIME,
  "fcm_token"           TEXT,
  "apns_token"          TEXT
);

-- ============================================================
-- Diet plans + meals
-- ============================================================

CREATE TABLE "diet_plans" (
  "id"          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"     UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "name"        VARCHAR(100) NOT NULL,
  "goal"        VARCHAR(50),
  "description" TEXT,
  "is_active"   BOOLEAN NOT NULL DEFAULT FALSE,
  "created_at"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at"  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX "idx_diet_plans_user_active" ON "diet_plans"("user_id", "is_active");

CREATE TABLE "meals" (
  "id"             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "diet_plan_id"   UUID NOT NULL REFERENCES "diet_plans"("id") ON DELETE CASCADE,
  "name"           VARCHAR(100) NOT NULL,
  "scheduled_time" TIME NOT NULL,
  "calories"       INTEGER,
  "protein_g"      DECIMAL(6,1),
  "carbs_g"        DECIMAL(6,1),
  "fat_g"          DECIMAL(6,1),
  "notes"          TEXT,
  "sort_order"     INTEGER NOT NULL DEFAULT 0,
  "created_at"     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "meal_ingredients" (
  "id"         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "meal_id"    UUID NOT NULL REFERENCES "meals"("id") ON DELETE CASCADE,
  "name"       VARCHAR(100) NOT NULL,
  "quantity"   VARCHAR(50),
  "calories"   INTEGER,
  "protein_g"  DECIMAL(6,1),
  "carbs_g"    DECIMAL(6,1),
  "fat_g"      DECIMAL(6,1),
  "sort_order" INTEGER NOT NULL DEFAULT 0
);

-- ============================================================
-- Supplement plans
-- ============================================================

CREATE TABLE "supplement_plans" (
  "id"         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"    UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "name"       VARCHAR(100) NOT NULL,
  "is_active"  BOOLEAN NOT NULL DEFAULT FALSE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX "idx_supplement_plans_user_active" ON "supplement_plans"("user_id", "is_active");

CREATE TABLE "supplements" (
  "id"                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "supplement_plan_id" UUID NOT NULL REFERENCES "supplement_plans"("id") ON DELETE CASCADE,
  "name"               VARCHAR(100) NOT NULL,
  "dosage"             VARCHAR(50),
  "form"               VARCHAR(30),
  "scheduled_time"     TIME NOT NULL,
  "timing_note"        VARCHAR(50),
  "frequency"          VARCHAR(20) NOT NULL DEFAULT 'daily',
  "frequency_days"     INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
  "stock_quantity"     INTEGER,
  "stock_alert_at"     INTEGER NOT NULL DEFAULT 7,
  "notes"              TEXT,
  "sort_order"         INTEGER NOT NULL DEFAULT 0,
  "created_at"         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- Daily schedule + uploaded plans
-- ============================================================

CREATE TABLE "daily_schedule_items" (
  "id"             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"        UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "date"           DATE NOT NULL,
  "item_type"      VARCHAR(20) NOT NULL,
  "reference_id"   UUID,
  "title"          VARCHAR(150) NOT NULL,
  "subtitle"       VARCHAR(200),
  "scheduled_time" TIME NOT NULL,
  "status"         VARCHAR(20) NOT NULL DEFAULT 'pending',
  "completed_at"   TIMESTAMPTZ,
  "notes"          TEXT,
  "sort_order"     INTEGER NOT NULL DEFAULT 0,
  "created_at"     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX "idx_schedule_user_date" ON "daily_schedule_items"("user_id", "date");
CREATE INDEX "idx_schedule_status" ON "daily_schedule_items"("user_id", "date", "status");

CREATE TABLE "uploaded_plans" (
  "id"          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"     UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "file_url"    TEXT NOT NULL,
  "file_type"   VARCHAR(20),
  "parsed_data" JSONB,
  "status"      VARCHAR(20) NOT NULL DEFAULT 'pending',
  "created_at"  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- Workouts
-- ============================================================

CREATE TABLE "exercises" (
  "id"                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"            UUID REFERENCES "users"("id") ON DELETE CASCADE,
  "name"               VARCHAR(100) NOT NULL,
  "category"           VARCHAR(30),
  "primary_muscle"     VARCHAR(30),
  "secondary_muscles"  VARCHAR(30)[] NOT NULL DEFAULT ARRAY[]::VARCHAR(30)[],
  "equipment"          VARCHAR(30),
  "is_unilateral"      BOOLEAN NOT NULL DEFAULT FALSE,
  "is_cardio"          BOOLEAN NOT NULL DEFAULT FALSE,
  "instructions"       TEXT,
  "created_at"         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX "idx_exercises_user" ON "exercises"("user_id");
CREATE INDEX "idx_exercises_category" ON "exercises"("category");

CREATE TABLE "workout_plans" (
  "id"            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"       UUID REFERENCES "users"("id") ON DELETE CASCADE,
  "name"          VARCHAR(100) NOT NULL,
  "goal"          VARCHAR(50),
  "split_type"    VARCHAR(30),
  "days_per_week" INTEGER,
  "description"   TEXT,
  "is_active"     BOOLEAN NOT NULL DEFAULT FALSE,
  "is_template"   BOOLEAN NOT NULL DEFAULT FALSE,
  "created_at"    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at"    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX "idx_workout_plans_user_active" ON "workout_plans"("user_id", "is_active");
CREATE INDEX "idx_workout_plans_template" ON "workout_plans"("is_template");

CREATE TABLE "workout_days" (
  "id"                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "workout_plan_id"        UUID NOT NULL REFERENCES "workout_plans"("id") ON DELETE CASCADE,
  "name"                   VARCHAR(100) NOT NULL,
  "day_of_week"            INTEGER,
  "sort_order"             INTEGER NOT NULL DEFAULT 0,
  "estimated_duration_min" INTEGER,
  "notes"                  TEXT
);

CREATE TABLE "workout_day_exercises" (
  "id"                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "workout_day_id"      UUID NOT NULL REFERENCES "workout_days"("id") ON DELETE CASCADE,
  "exercise_id"         UUID NOT NULL REFERENCES "exercises"("id"),
  "sort_order"          INTEGER NOT NULL DEFAULT 0,
  "target_sets"         INTEGER NOT NULL,
  "target_reps"         VARCHAR(20),
  "target_weight_kg"    DECIMAL(6,1),
  "target_rpe"          DECIMAL(3,1),
  "target_duration_sec" INTEGER,
  "target_distance_km"  DECIMAL(6,2),
  "rest_seconds"        INTEGER,
  "tempo"               VARCHAR(10),
  "superset_group"      VARCHAR(10),
  "progression_kg"      DECIMAL(4,1) NOT NULL DEFAULT 0,
  "notes"               TEXT
);

CREATE TABLE "workout_sessions" (
  "id"             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"        UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "workout_day_id" UUID REFERENCES "workout_days"("id"),
  "date"           DATE NOT NULL,
  "started_at"     TIMESTAMPTZ,
  "completed_at"   TIMESTAMPTZ,
  "duration_min"   INTEGER,
  "bodyweight_kg"  DECIMAL(5,1),
  "energy_level"   INTEGER,
  "notes"          TEXT,
  "status"         VARCHAR(20) NOT NULL DEFAULT 'in_progress',
  "created_at"    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX "idx_workout_sessions_user_date" ON "workout_sessions"("user_id", "date");
CREATE INDEX "idx_workout_sessions_user_status" ON "workout_sessions"("user_id", "status");

CREATE TABLE "workout_sets" (
  "id"           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "session_id"   UUID NOT NULL REFERENCES "workout_sessions"("id") ON DELETE CASCADE,
  "exercise_id"  UUID NOT NULL REFERENCES "exercises"("id"),
  "set_number"   INTEGER NOT NULL,
  "reps"         INTEGER,
  "weight_kg"    DECIMAL(6,1),
  "rpe"          DECIMAL(3,1),
  "duration_sec" INTEGER,
  "distance_km"  DECIMAL(6,2),
  "is_warmup"    BOOLEAN NOT NULL DEFAULT FALSE,
  "is_failure"   BOOLEAN NOT NULL DEFAULT FALSE,
  "rest_seconds" INTEGER,
  "notes"        TEXT,
  "logged_at"    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX "idx_workout_sets_session" ON "workout_sets"("session_id");
CREATE INDEX "idx_workout_sets_exercise" ON "workout_sets"("exercise_id");

CREATE TABLE "personal_records" (
  "id"          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"     UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "exercise_id" UUID NOT NULL REFERENCES "exercises"("id"),
  "record_type" VARCHAR(20) NOT NULL,
  "value"       DECIMAL(8,2) NOT NULL,
  "unit"        VARCHAR(10) NOT NULL,
  "set_id"      UUID REFERENCES "workout_sets"("id"),
  "achieved_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX "idx_personal_records_user_exercise" ON "personal_records"("user_id", "exercise_id");
